import { db, type ReadFlowDB } from './database';
import type { BackupData, Book, Bookmark, Highlight, VocabWord } from './types';
const id=()=>crypto.randomUUID(); const now=()=>Date.now(); const bufferToBase64=(buffer:ArrayBuffer)=>{let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}; const base64ToBuffer=(value:string)=>{const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer};
export const makeRepositories=(database:ReadFlowDB=db)=>({
 books:{ all:()=>database.books.toArray(), get:(key:string)=>database.books.get(key), add:(data:Omit<Book,'id'|'addedAt'|'lastReadAt'|'currentPage'|'rotation'>)=>{const t=now(),book:Book={...data,id:id(),addedAt:t,lastReadAt:t,currentPage:1,rotation:0};return database.books.add(book).then(()=>book)}, rename:(key:string,title:string)=>database.books.update(key,{title:title.trim()}), progress:(key:string,page:number)=>database.books.update(key,{currentPage:page,lastReadAt:now()}), rotation:(key:string,rotation:number)=>database.books.update(key,{rotation}), remove:async(key:string)=>database.transaction('rw',database.books,database.bookmarks,database.highlights,database.vocabulary,async()=>{await Promise.all([database.books.delete(key),database.bookmarks.where('bookId').equals(key).delete(),database.highlights.where('bookId').equals(key).delete(),database.vocabulary.where('bookId').equals(key).delete()])})},
 bookmarks:{ count:()=>database.bookmarks.count(), forBook:(bookId:string)=>database.bookmarks.where('bookId').equals(bookId).sortBy('page'), toggle:async(bookId:string,page:number)=>{const old=await database.bookmarks.where('[bookId+page]').equals([bookId,page]).first();if(old){await database.bookmarks.delete(old.id);return false}await database.bookmarks.add({id:id(),bookId,page,createdAt:now()});return true}, remove:(key:string)=>database.bookmarks.delete(key)},
 highlights:{ forBook:(bookId:string)=>database.highlights.where('bookId').equals(bookId).sortBy('createdAt'), add:(data:Omit<Highlight,'id'|'createdAt'>)=>{const item={...data,id:id(),createdAt:now()};return database.highlights.add(item).then(()=>item)}, update:(key:string,changes:Partial<Pick<Highlight,'note'|'color'>>)=>database.highlights.update(key,changes), remove:(key:string)=>database.highlights.delete(key)},
 vocabulary:{ count:()=>database.vocabulary.count(), forBook:(bookId:string)=>database.vocabulary.where('bookId').equals(bookId).sortBy('createdAt'), add:(data:Omit<VocabWord,'id'|'createdAt'|'word'> & {word:string})=>{const item={...data,word:data.word.trim().toLowerCase(),id:id(),createdAt:now()};return database.vocabulary.add(item).then(()=>item)}, update:(key:string,changes:Partial<Pick<VocabWord,'word'|'meaning'|'example'>>)=>database.vocabulary.update(key,{...changes,...(changes.word?{word:changes.word.trim().toLowerCase()}:{})}), remove:(key:string)=>database.vocabulary.delete(key)},
 backup:{ export:async():Promise<BackupData>=>{const books=await database.books.toArray();return {version:1,exportedAt:now(),books:books.map(b=>({...b,fileData:bufferToBase64(b.fileData)})),bookmarks:await database.bookmarks.toArray(),highlights:await database.highlights.toArray(),vocabulary:await database.vocabulary.toArray()}}, import:async(data:BackupData)=>{if(!data||data.version!==1||!Array.isArray(data.books)||!Array.isArray(data.bookmarks)||!Array.isArray(data.highlights)||!Array.isArray(data.vocabulary)||data.books.some(b=>!b||typeof b.id!=='string'||typeof b.title!=='string'||typeof b.fileData!=='string'||typeof b.totalPages!=='number'))throw new Error('Tệp sao lưu không hợp lệ');let books:Book[];try{books=data.books.map(b=>({...b,fileData:base64ToBuffer(b.fileData)}))}catch{throw new Error('Dữ liệu PDF trong bản sao lưu bị hỏng')}await database.transaction('rw',database.books,database.bookmarks,database.highlights,database.vocabulary,async()=>{await Promise.all([database.books.clear(),database.bookmarks.clear(),database.highlights.clear(),database.vocabulary.clear()]);await database.books.bulkPut(books);await database.bookmarks.bulkPut(data.bookmarks);await database.highlights.bulkPut(data.highlights);await database.vocabulary.bulkPut(data.vocabulary)})}}
});
export const repositories=makeRepositories();
