import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import fastifyStatic from '@fastify/static';
import type {ServerDatabase} from './db.js';
import {openDatabase} from './db.js';

const MAX_PDF_SIZE=100*1024*1024;
type Row=Record<string,unknown>;
const mapBook=(row:Row)=>({id:row.id,title:row.title,fileName:row.file_name,totalPages:row.total_pages,currentPage:row.current_page,rotation:row.rotation,addedAt:row.added_at,lastReadAt:row.last_read_at,fileSize:row.file_size,fileUrl:`/api/books/${row.id}/file`});
const mapChild=(row:Row)=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase()),value]));
const requiredString=(value:unknown,name:string)=>{if(typeof value!=='string'||!value.trim())throw Object.assign(new Error(`${name} không hợp lệ`),{statusCode:400});return value.trim()};
const requiredNumber=(value:unknown,name:string)=>{const number=Number(value);if(!Number.isFinite(number))throw Object.assign(new Error(`${name} không hợp lệ`),{statusCode:400});return number};

export async function buildApp(options:{database?:ServerDatabase;dataDir?:string;serveStatic?:boolean}={}){
 const dataDir=options.dataDir||process.env.DATA_DIR||path.resolve('data'),booksDir=path.join(dataDir,'books');
 fs.mkdirSync(booksDir,{recursive:true});
 const database=options.database||openDatabase(dataDir),ownsDatabase=!options.database;
 const app=Fastify({logger:process.env.NODE_ENV!=='test',bodyLimit:150*1024*1024});
 await app.register(multipart,{limits:{fileSize:MAX_PDF_SIZE,files:1,fields:20}});
 app.addHook('onClose',async()=>{if(ownsDatabase)database.close()});
 app.setErrorHandler((error,request,reply)=>{const status=(error as {statusCode?:number}).statusCode||500;request.log.error(error);void reply.status(status).send({error:{code:status===404?'NOT_FOUND':'REQUEST_FAILED',message:status===500?'Lỗi máy chủ':error instanceof Error?error.message:String(error),requestId:request.id}})});
 app.get('/api/health',async()=>({status:'ok'}));
 app.get('/api/stats',async()=>({bookmarks:(database.prepare('SELECT COUNT(*) count FROM bookmarks').get() as {count:number}).count,vocabulary:(database.prepare('SELECT COUNT(*) count FROM vocabulary').get() as {count:number}).count}));
 app.get('/api/books',async()=>database.prepare('SELECT * FROM books ORDER BY last_read_at DESC').all().map(row=>mapBook(row as Row)));
 app.get('/api/books/:id',async request=>{const {id}=request.params as {id:string},row=database.prepare('SELECT * FROM books WHERE id=?').get(id) as Row|undefined;if(!row)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});return mapBook(row)});
 app.post('/api/books',async(request,reply)=>{const parts=request.parts();let fileName='',title='',id='',totalPages=0,temp='',size=0;const hash=crypto.createHash('sha256');try{for await(const part of parts){if(part.type==='file'){fileName=part.filename;temp=path.join(booksDir,`.upload-${crypto.randomUUID()}`);const output=fs.createWriteStream(temp,{flags:'wx'});for await(const chunk of part.file){size+=chunk.length;if(size>MAX_PDF_SIZE)throw Object.assign(new Error('PDF vượt quá 100 MB'),{statusCode:413});hash.update(chunk);if(!output.write(chunk))await new Promise(resolve=>output.once('drain',resolve))}await new Promise<void>((resolve,reject)=>output.end((error?:Error|null)=>error?reject(error):resolve()))}else{const value=String(part.value);if(part.fieldname==='id')id=value;if(part.fieldname==='title')title=value;if(part.fieldname==='totalPages')totalPages=Number(value)}}if(!temp||size<5)throw Object.assign(new Error('Thiếu file PDF'),{statusCode:400});const header=Buffer.alloc(5);const handle=fs.openSync(temp,'r');fs.readSync(handle,header,0,5,0);fs.closeSync(handle);if(header.toString()!=='%PDF-')throw Object.assign(new Error('File không phải PDF hợp lệ'),{statusCode:415});id=id||crypto.randomUUID();title=requiredString(title||fileName.replace(/\.pdf$/i,''),'Tên sách');totalPages=Math.max(1,Math.trunc(requiredNumber(totalPages,'Số trang')));const destination=path.join(booksDir,`${id}.pdf`);if(database.prepare('SELECT id FROM books WHERE id=?').get(id))throw Object.assign(new Error('Sách đã tồn tại'),{statusCode:409});fs.renameSync(temp,destination);temp='';const now=Date.now();database.prepare('INSERT INTO books(id,title,file_name,total_pages,current_page,rotation,added_at,last_read_at,updated_at,file_size,sha256) VALUES(?,?,?,?,1,0,?,?,?,?,?)').run(id,title,fileName,totalPages,now,now,now,size,hash.digest('hex'));return reply.status(201).send(mapBook(database.prepare('SELECT * FROM books WHERE id=?').get(id) as Row))}finally{if(temp)fs.rmSync(temp,{force:true})}});
 app.patch('/api/books/:id',async request=>{const {id}=request.params as {id:string},title=requiredString((request.body as {title?:unknown})?.title,'Tên sách'),now=Date.now();const result=database.prepare('UPDATE books SET title=?,updated_at=? WHERE id=?').run(title,now,id);if(!result.changes)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});return {ok:true}});
 app.put('/api/books/:id/progress',async request=>{const {id}=request.params as {id:string},page=Math.max(1,Math.trunc(requiredNumber((request.body as {page?:unknown})?.page,'Trang'))),now=Date.now();const result=database.prepare('UPDATE books SET current_page=MIN(?,total_pages),last_read_at=?,updated_at=? WHERE id=?').run(page,now,now,id);if(!result.changes)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});return {ok:true}});
 app.put('/api/books/:id/rotation',async request=>{const {id}=request.params as {id:string},rotation=requiredNumber((request.body as {rotation?:unknown})?.rotation,'Góc xoay'),now=Date.now();const result=database.prepare('UPDATE books SET rotation=?,updated_at=? WHERE id=?').run(rotation,now,id);if(!result.changes)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});return {ok:true}});
 app.delete('/api/books/:id',async(request,reply)=>{const {id}=request.params as {id:string};const result=database.prepare('DELETE FROM books WHERE id=?').run(id);if(!result.changes)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});fs.rmSync(path.join(booksDir,`${id}.pdf`),{force:true});return reply.status(204).send()});
 app.get('/api/books/:id/file',async(request,reply)=>{const {id}=request.params as {id:string},row=database.prepare('SELECT file_name FROM books WHERE id=?').get(id) as {file_name:string}|undefined;if(!row)throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});const file=path.join(booksDir,`${id}.pdf`),stat=fs.statSync(file),range=request.headers.range;reply.header('Accept-Ranges','bytes').header('Content-Type','application/pdf').header('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(row.file_name)}`);if(range){const match=/bytes=(\d*)-(\d*)/.exec(range);if(match){const start=match[1]?Number(match[1]):0,end=match[2]?Math.min(Number(match[2]),stat.size-1):stat.size-1;if(start<=end&&start<stat.size)return reply.status(206).headers({'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Content-Length':end-start+1}).send(fs.createReadStream(file,{start,end}))}}return reply.header('Content-Length',stat.size).send(fs.createReadStream(file))});

 const childConfigs={bookmarks:{table:'bookmarks',fields:['page'],order:'page'},highlights:{table:'highlights',fields:['page','text','color','note'],order:'created_at'},vocabulary:{table:'vocabulary',fields:['word','meaning','example','page'],order:'created_at'}} as const;
 for(const [resource,config] of Object.entries(childConfigs)){
  app.get(`/api/books/:bookId/${resource}`,async request=>{const {bookId}=request.params as {bookId:string};return database.prepare(`SELECT * FROM ${config.table} WHERE book_id=? ORDER BY ${config.order}`).all(bookId).map(row=>mapChild(row as Row))});
  app.post(`/api/books/:bookId/${resource}`,async(request,reply)=>{const {bookId}=request.params as {bookId:string},body=(request.body||{}) as Row,id=typeof body.id==='string'?body.id:crypto.randomUUID(),now=Date.now();if(!database.prepare('SELECT id FROM books WHERE id=?').get(bookId))throw Object.assign(new Error('Không tìm thấy sách'),{statusCode:404});const values=config.fields.map(field=>field==='page'?requiredNumber(body[field],field):field==='word'?requiredString(body[field],field).toLowerCase():field==='note'||field==='example'?(body[field]??null):requiredString(body[field],field));database.prepare(`INSERT INTO ${config.table}(id,book_id,${config.fields.join(',')},created_at${resource==='bookmarks'?'':',updated_at'}) VALUES(${Array(3+config.fields.length+(resource==='bookmarks'?0:1)).fill('?').join(',')})`).run(id,bookId,...values,typeof body.createdAt==='number'?body.createdAt:now,...(resource==='bookmarks'?[]:[now]));return reply.status(201).send(mapChild(database.prepare(`SELECT * FROM ${config.table} WHERE id=?`).get(id) as Row))});
 }
 app.post('/api/books/:bookId/bookmarks/toggle',async request=>{const {bookId}=request.params as {bookId:string},page=requiredNumber((request.body as {page?:unknown})?.page,'Trang'),existing=database.prepare('SELECT id FROM bookmarks WHERE book_id=? AND page=?').get(bookId,page) as {id:string}|undefined;if(existing){database.prepare('DELETE FROM bookmarks WHERE id=?').run(existing.id);return {active:false}}database.prepare('INSERT INTO bookmarks(id,book_id,page,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),bookId,page,Date.now());return {active:true}});
 for(const resource of ['bookmarks','highlights','vocabulary'] as const)app.delete(`/api/${resource}/:id`,async(request,reply)=>{const {id}=request.params as {id:string};database.prepare(`DELETE FROM ${resource} WHERE id=?`).run(id);return reply.status(204).send()});
 app.patch('/api/highlights/:id',async request=>{const {id}=request.params as {id:string},body=request.body as {note?:string;color?:string};database.prepare('UPDATE highlights SET note=COALESCE(?,note),color=COALESCE(?,color),updated_at=? WHERE id=?').run(body.note??null,body.color??null,Date.now(),id);return {ok:true}});
 app.patch('/api/vocabulary/:id',async request=>{const {id}=request.params as {id:string},body=request.body as {word?:string;meaning?:string;example?:string};database.prepare('UPDATE vocabulary SET word=COALESCE(?,word),meaning=COALESCE(?,meaning),example=COALESCE(?,example),updated_at=? WHERE id=?').run(body.word?.trim().toLowerCase()||null,body.meaning?.trim()||null,body.example??null,Date.now(),id);return {ok:true}});
 app.get('/api/export',async(_request,reply)=>{const books=(database.prepare('SELECT * FROM books').all() as Row[]).map(book=>({...book,fileData:fs.readFileSync(path.join(booksDir,`${book.id}.pdf`)).toString('base64')}));const backup={version:2,exportedAt:Date.now(),books,bookmarks:database.prepare('SELECT * FROM bookmarks').all(),highlights:database.prepare('SELECT * FROM highlights').all(),vocabulary:database.prepare('SELECT * FROM vocabulary').all()};return reply.header('Content-Type','application/json').send(backup)});
 app.post('/api/import',async request=>{const input=request.body as {version?:number;books?:Row[];bookmarks?:Row[];highlights?:Row[];vocabulary?:Row[]};if(input.version!==2||!Array.isArray(input.books)||!Array.isArray(input.bookmarks)||!Array.isArray(input.highlights)||!Array.isArray(input.vocabulary))throw Object.assign(new Error('Tệp sao lưu không hợp lệ'),{statusCode:400});const data={version:input.version,books:input.books,bookmarks:input.bookmarks,highlights:input.highlights,vocabulary:input.vocabulary};const staging=path.join(dataDir,`.restore-${crypto.randomUUID()}`);fs.mkdirSync(staging,{recursive:true});try{for(const book of data.books){const id=requiredString(book.id,'ID sách'),encoded=requiredString(book.fileData,'Dữ liệu PDF'),content=Buffer.from(encoded,'base64');if(content.subarray(0,5).toString()!=='%PDF-')throw new Error('PDF trong bản sao lưu bị hỏng');fs.writeFileSync(path.join(staging,`${id}.pdf`),content)}const restore=database.transaction(()=>{database.exec('DELETE FROM bookmarks; DELETE FROM highlights; DELETE FROM vocabulary; DELETE FROM books;');const insertBook=database.prepare('INSERT INTO books(id,title,file_name,total_pages,current_page,rotation,added_at,last_read_at,updated_at,file_size,sha256) VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const book of data.books)insertBook.run(book.id,book.title,book.file_name,book.total_pages,book.current_page,book.rotation,book.added_at,book.last_read_at,book.updated_at,book.file_size,book.sha256);for(const item of data.bookmarks)database.prepare('INSERT INTO bookmarks(id,book_id,page,created_at) VALUES(?,?,?,?)').run(item.id,item.book_id,item.page,item.created_at);for(const item of data.highlights)database.prepare('INSERT INTO highlights(id,book_id,page,text,color,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(item.id,item.book_id,item.page,item.text,item.color,item.note,item.created_at,item.updated_at);for(const item of data.vocabulary)database.prepare('INSERT INTO vocabulary(id,book_id,word,meaning,example,page,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(item.id,item.book_id,item.word,item.meaning,item.example,item.page,item.created_at,item.updated_at)});restore();for(const file of fs.readdirSync(booksDir))if(file.endsWith('.pdf'))fs.rmSync(path.join(booksDir,file));for(const file of fs.readdirSync(staging))fs.renameSync(path.join(staging,file),path.join(booksDir,file));return {ok:true}}finally{fs.rmSync(staging,{recursive:true,force:true})}});

 if(options.serveStatic!==false&&fs.existsSync(path.resolve('dist'))){await app.register(fastifyStatic,{root:path.resolve('dist')});app.setNotFoundHandler((request,reply)=>request.url.startsWith('/api/')?reply.status(404).send({error:{code:'NOT_FOUND',message:'Không tìm thấy'}}):reply.sendFile('index.html'))}
 return app;
}
